name = "dazpm-demo"
version = "0.1.0"
description = "Demo package for dazpm"
author = "dazui-py"
license = "MIT"

[shell]
supports = ["zsh"]

[install]
bins = ["bin/daz-demo"]
plugins = ["plugins/nao-existe.zsh"]
functions = []
completions = []
